/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_checkHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User registration */
        post: operations["AuthController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User login */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user info from token */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all expert profiles */
        get: operations["ExpertController_getAllProfiles"];
        put?: never;
        /** Expert profile creation */
        post: operations["ExpertController_createProfile"];
        delete?: never;
        options?: never;
        head?: never;
        /** Update profile of logged expert user */
        patch: operations["ExpertController_updateProfile"];
        trace?: never;
    };
    "/expert/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get currently logged expert profile */
        get: operations["ExpertController_getLoggedExpertProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/expert/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get expert profile by id */
        get: operations["ExpertController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        UserRole: "CLIENT" | "EXPERT" | "ADMIN";
        RegisterDto: {
            /** @example test@test.com */
            email: string;
            /** @example test123# */
            password: string;
            /** @example CLIENT */
            role?: components["schemas"]["UserRole"];
        };
        RegisterResponseDto: {
            /** @example uuid-here */
            id: string;
            /** @example test@gmail.com */
            email: string;
            /** @enum {string} */
            role: "CLIENT" | "EXPERT" | "ADMIN";
        };
        LoginDto: {
            /** @example test@test.com */
            email: string;
            /** @example test123# */
            password: string;
        };
        LoginResponseDto: {
            /** @example uuid-here */
            id: string;
            /** @example test@gmail.com */
            email: string;
            /** @enum {string} */
            role: "CLIENT" | "EXPERT" | "ADMIN";
            /** @example accessTokenHere */
            accessToken: string;
        };
        JwtPayloadDto: Record<string, never>;
        PricingResponseDto: {
            /** @example uuid-here */
            id: string;
            /** @example uuid-here */
            expertProfileId: string;
            /** @example MIN_15 */
            consultationDuration: string;
            /** @example 12000 */
            price: number;
        };
        /** @enum {string} */
        Specialization: "TAX_LAW" | "CORPORATE_LAW" | "CIVIL_LAW" | "ACCOUNTING" | "PAYROLL" | "FINANCIAL_PLANNING" | "INVESTMENT_ADVISORY" | "INSURANCE";
        ExpertProfileResponseDto: {
            /** @example uuid-here */
            id: string;
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example Very good and respected accountant and tax advisor */
            bio: string;
            /**
             * @example [
             *       {
             *         "id": "uuid-here",
             *         "expertProfileId": "uuid-here",
             *         "consultationDuration": "MIN_10",
             *         "price": 5000
             *       },
             *       {
             *         "id": "uuid-here",
             *         "expertProfileId": "uuid-here",
             *         "consultationDuration": "MIN_20",
             *         "price": 8000
             *       }
             *     ]
             */
            pricings: components["schemas"]["PricingResponseDto"][];
            /**
             * @example [
             *       "TAX_LAW",
             *       "CORPORATE_LAW",
             *       "ACCOUNTING"
             *     ]
             */
            specializations: components["schemas"]["Specialization"][];
        };
        PricingDto: {
            /** @example MIN_15 */
            duration: string;
            /** @example 12000 */
            price: number;
        };
        CreateExpertProfileDto: {
            /** @example John */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /** @example John Doe bio */
            bio: string;
            /**
             * @example [
             *       {
             *         "duration": "MIN_10",
             *         "price": 2000
             *       },
             *       {
             *         "duration": "MIN_20",
             *         "price": 3000
             *       },
             *       {
             *         "duration": "MIN_60",
             *         "price": 7500
             *       }
             *     ]
             */
            pricings: components["schemas"]["PricingDto"][];
            /**
             * @example [
             *       "TAX_LAW",
             *       "CORPORATE_LAW",
             *       "ACCOUNTING"
             *     ]
             */
            specializations: components["schemas"]["Specialization"][];
        };
        UpdateExpertProfileDto: {
            /** @example John */
            firstName?: string;
            /** @example Doe */
            lastName?: string;
            /** @example John Doe bio */
            bio?: string;
            /**
             * @example [
             *       {
             *         "duration": "MIN_10",
             *         "price": 2000
             *       },
             *       {
             *         "duration": "MIN_20",
             *         "price": 3000
             *       },
             *       {
             *         "duration": "MIN_60",
             *         "price": 7500
             *       }
             *     ]
             */
            pricings?: components["schemas"]["PricingDto"][];
            /**
             * @example [
             *       "TAX_LAW",
             *       "CORPORATE_LAW",
             *       "ACCOUNTING",
             *       "PAYROLL"
             *     ]
             */
            specializations?: components["schemas"]["Specialization"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_checkHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Email is already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wrong credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JwtPayloadDto"];
                };
            };
            /** @description Wrong or missing token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpertController_getAllProfiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertProfileResponseDto"][];
                };
            };
        };
    };
    ExpertController_createProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpertProfileDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertProfileResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description This user already has expert profile created */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpertController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpertProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertProfileResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expert profile for this user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description One duration can have only one price */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpertController_getLoggedExpertProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertProfileResponseDto"];
                };
            };
            /** @description Expert profile for logged user not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ExpertController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpertProfileResponseDto"];
                };
            };
            /** @description Expert profile with given id doesn't exist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
