/**
 * This file is auto-generated by scripts/generate-types.mjs.
 * Do not edit it manually — run `npm run generate:api-types` to regenerate.
 */
import type { components } from "@/lib/api-types";

export type UserRole = components["schemas"]["UserRole"];
export type RegisterDto = components["schemas"]["RegisterDto"];
export type RegisterResponseDto = components["schemas"]["RegisterResponseDto"];
export type LoginDto = components["schemas"]["LoginDto"];
export type LoginResponseDto = components["schemas"]["LoginResponseDto"];
export type JwtPayloadDto = components["schemas"]["JwtPayloadDto"];
export type PricingResponseDto = components["schemas"]["PricingResponseDto"];
export type Specialization = components["schemas"]["Specialization"];
export type ExpertProfileResponseDto = components["schemas"]["ExpertProfileResponseDto"];
export type PricingDto = components["schemas"]["PricingDto"];
export type CreateExpertProfileDto = components["schemas"]["CreateExpertProfileDto"];
export type UpdateExpertProfileDto = components["schemas"]["UpdateExpertProfileDto"];
