#!/usr/bin/env node
/**
 * Reads the auto-generated src/lib/api-types.ts and re-exports every
 * components.schemas entry as a named type alias in src/lib/types.ts.
 *
 * Run via: npm run generate:api-types
 */

import { readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const apiTypesPath = resolve(__dirname, "../src/lib/api-types.ts");
const outputPath = resolve(__dirname, "../src/lib/types.ts");

const content = readFileSync(apiTypesPath, "utf-8");

// Extract the schemas block between `    schemas: {` and the closing `    };`
const schemasBlock = content.match(/    schemas:\s*\{([\s\S]*?)\n    \};/);
if (!schemasBlock) {
  console.error("❌ Could not find schemas block in api-types.ts");
  process.exit(1);
}

// Schema keys sit at exactly 8 spaces of indentation
const keyRegex = /^        (\w+):/gm;
const names = [];
let match;
while ((match = keyRegex.exec(schemasBlock[1])) !== null) {
  names.push(match[1]);
}

if (names.length === 0) {
  console.error("❌ No schema names found in api-types.ts");
  process.exit(1);
}

const output = [
  "/**",
  " * This file is auto-generated by scripts/generate-types.mjs.",
  " * Do not edit it manually — run `npm run generate:api-types` to regenerate.",
  " */",
  `import type { components } from "@/lib/api-types";`,
  "",
  ...names.map(
    (name) => `export type ${name} = components["schemas"]["${name}"];`,
  ),
  "",
].join("\n");

writeFileSync(outputPath, output, "utf-8");
console.log(`✅ Generated ${names.length} type aliases → src/lib/types.ts`);
